nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']  # tu frontend Vite
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET','POST','OPTIONS']
            allow_headers: ['Content-Type','Authorization']
            max_age: 3600
            allow_credentials: true
